# WORKFLOW FILE GENERIC STRUCTURE:
# --------------------------------
# workflow name
# trigger
# jobs (each job starts with any required setup for that job)
# actions / steps

name: on_push

on:
  push:
    branch:
    - "**"  # run on all branches

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true

    steps:
      # Capture build start time on linux
#      - name: Record start time
#        run: echo START_TIME=$(date +%s) >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 16

      - name: Install Chrome 152
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=152.0.7977.64-1     

     # Capture test start time - I feel this gives a more accurate measure of the actual test run time
      - name: Record start time
        run: echo START_TIME=$(date +%s) >> $GITHUB_ENV

      - name: Run selenium tests with maven
        working-directory: webdriver_java
        run: mvn test

      # Capture end timestamp regardless of test result. And compute test duration
      - name: Record test end time
        if: always()
        run: expr $(date +%s) - ${START_TIME}

